pipeline:
  docker:
    image: metwork/drone-docker-specific-image:latest
    pull: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/root
    commands:
      - docker build -t metwork/centos6:latest .
      - docker push metwork/centos6:latest
    when:
      event: push

branches: [ master ]
